name = "Firestore"
uuid = "e3a022ed-41f3-4428-9302-72033236174a"
authors = ["joshday <emailjoshday@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
